before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.goversion={{.Env.GOVERSION}}
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
dockers:
  - image_templates:
      - "8398a7/gen-lgtm:latest"
      - "8398a7/gen-lgtm:{{.Tag}}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - tap:
      owner: 8398a7
      name: homebrew-gen-lgtm
      token: "{{ .Env.GITHUB_TOKEN }}"
    url_template: "http://github.com/8398a7/gen-lgtm/releases/download/{{ .Tag }}/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}.tar.gz"
    commit_author:
      name: 8398a7
      email: 8398a7@gmail.com
    homepage: https://github.com/8398a7/gen-lgtm
    description: Convert your favorite images to LGTM images.
    install: |
      bin.install "gen-lgtm"
